name: Java Selenium Tests

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      # 3. Cache Maven dependencies
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # 4. Install dependencies & run tests (TestNG)
      - name: Run Selenium Tests
        run: mvn clean test -Dsurefire.useFile=false

      # 5. Collect Allure results
      - name: Collect Allure results
        if: always()
        run: |
          mkdir -p allure-results
          cp -r target/surefire-reports/* allure-results/ || true

      # 6. Upload Allure as artifact
      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results
          path: allure-results/

      # 7. Send Allure JSON to n8n webhook
      - name: Send Allure JSON to n8n
        if: always()
        run: |
          if [ -f "allure-results/categories.json" ]; then
            curl -X POST "${{ secrets.N8N_WEBHOOK_URL }}" \
              -H "Content-Type: application/json" \
              -d @allure-results/categories.json || echo "Failed to send results"
          else
            echo '{"message":"No Allure categories.json found"}' | \
            curl -X POST "${{ secrets.N8N_WEBHOOK_URL }}" \
              -H "Content-Type: application/json" \
              -d @- || true
          fi
